name: finbank
version: '1.0.0'
config-version: 2
profile: finbank
require-dbt-version: ">=1.12.0,<2.0.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  finbank:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table
