select
    trim(event_id) as event_id,
    trim(transaction_id) as transaction_id,
    trim(event_type) as event_type,
    schema_version,
    event_timestamp,
    transaction_timestamp,
    trim(customer_id) as customer_id,
    trim(account_id) as account_id,
    trim(merchant_id) as merchant_id,
    amount::numeric(18, 2) as amount,
    trim(currency) as currency,
    trim(transaction_type) as transaction_type,
    trim(country) as country,
    trim(city) as city,
    trim(payment_method) as payment_method,
    trim(status) as status,
    payload,
    kafka_topic,
    kafka_partition,
    kafka_offset,
    ingested_at,
    transaction_timestamp::date as transaction_date
from {{ source('finbank_raw', 'transaction_events') }}
